// These are large types that represent reponses from our api
export type Player = {
  id: number;
  name: string;
  position: 'C' | 'RW' | 'LW' | 'RD' | 'LD';
  league: number;
  team: string;
  season: number;
  gamesPlayed: number;
  timeOnIce: number;
  goals: number;
  assists: number;
  points: number;
  plusMinus: number;
  pim: number;
  ppGoals: number;
  ppAssists: number;
  ppPoints: number;
  ppTimeOnIce: number;
  shGoals: number;
  shAssists: number;
  shPoints: number;
  shTimeOnIce: number;
  fights: number;
  fightWins: number;
  fightLosses: number;
  faceoffs: number | undefined;
  faceoffWins: number | undefined;
  gwg: number | undefined;
  hits: number;
  giveaways: number;
  takeaways: number;
  shotsBlocked: number;
  shotsOnGoal: number;
  gameRating: number;
  offensiveGameRating: number;
  defensiveGameRating: number;
  teamID: number;
};

export type PlayerInfo = {
  height: number;
  id: number;
  league: number;
  season: number;
  weight: number;
  team: string;
  teamID: number;
  position: 'C' | 'LW' | 'RW' | 'LD' | 'RD';
};

export type PlayerWithAdvancedStats = Player & {
  advancedStats: {
    PDO: number;
    GF60: number;
    GA60: number;
    SF60: number;
    SA60: number;
    CF: number;
    CA: number;
    CFPct: number;
    CFPctRel: number;
    FF: number;
    FA: number;
    FFPct: number;
    FFPctRel: number;
  };
};

export type Goalie = {
  id: number;
  name: string;
  position: 'G';
  league: number;
  team: string;
  season: number;
  gamesPlayed: number;
  minutes: number;
  wins: number;
  losses: number;
  ot: number;
  shotsAgainst: number;
  saves: number;
  goalsAgainst: number;
  gaa: number;
  shutouts: number;
  savePct: number;
  gameRating: number;
  teamID: number;
};

export type GoalieInfo = {
  height: number;
  id: number;
  league: number;
  season: number;
  weight: number;
  team: string;
  teamID: number;
};

export type Team = {
  id: number;
  season: number;
  conference: number;
  division: number;
  name: string;
  nameDetails: { first: string; second: string };
  abbreviation: string;
  location: string;
  colors: { primary: string; secondary: string; text: string };
  stats: {
    wins: number;
    losses: number;
    overtimeLosses: number;
    shootoutWins: number;
    shootoutLosses: number;
    points: number;
    goalsFor: number;
    goalsAgainst: number;
    winPercent: number;
  };
};

export type PlayerRatings = {
  screening: number;
  gettingOpen: number;
  passing: number;
  puckhandling: number;
  shootingAccuracy: number;
  shootingRange: number;
  offensiveRead: number;
  checking: number;
  hitting: number;
  positioning: number;
  stickchecking: number;
  shotBlocking: number;
  faceoffs: number;
  defensiveRead: number;
  acceleration: number;
  agility: number;
  balance: number;
  speed: number;
  stamina: number;
  strength: number;
  fighting: number;
  aggression: number;
  bravery: number;
  appliedTPE?: number;
};

export type GoalieRatings = {
  blocker: number;
  glove: number;
  passing: number;
  pokeCheck: number;
  positioning: number;
  rebound: number;
  recovery: number;
  puckhandling: number;
  lowShots: number;
  reflexes: number;
  skating: number;
  mentalToughness: number;
  goalieStamina: number;
  appliedTPE?: number;
};

export type InternalPlayerRatings = {
  Name: string;
  Abbr: string;
  PlayerID: number;
  LeagueID: number;
  SeasonID: number;
  G: number;
  LD: number;
  RD: number;
  LW: number;
  C: number;
  RW: number;
  Aggression: number;
  Bravery: number;
  Determination: number;
  Teamplayer: number;
  Leadership: number;
  Temperament: number;
  Professionalism: number;
  MentalToughness: number;
  GoalieStamina: number;
  Acceleration: number;
  Agility: number;
  Balance: number;
  Speed: number;
  Stamina: number;
  Strength: number;
  Fighting: number;
  Screening: number;
  GettingOpen: number;
  Passing: number;
  PuckHandling: number;
  ShootingAccuracy: number;
  ShootingRange: number;
  OffensiveRead: number;
  Checking: number;
  Faceoffs: number;
  Hitting: number;
  Positioning: number;
  ShotBlocking: number;
  Stickchecking: number;
  DefensiveRead: number;
  GPositioning: number;
  GPassing: number;
  GPokecheck: number;
  Blocker: number;
  Glove: number;
  Rebound: number;
  Recovery: number;
  GPuckhandling: number;
  LowShots: number;
  GSkating: number;
  Reflexes: number;
  Skating: number;
  Shooting: number;
  Playmaking: number;
  Defending: number;
  Physicality: number;
  Conditioning: number;
  Character: number;
  HockeySense: number;
  GoalieTechnique: number;
  GoalieOverallPositioning: number;
};

export type Skater_Boxscore = {
  season: number;
  league: number;
  gameID: number;
  slug: number;
  playerID: number;
  name: string;
  teamID: number;
  teamAbbr: string;
  isHome: boolean;
  opponentTeamID: number;
  opponentAbbr: string;
  date: string;
  type: string;
  gameRating: number;
  offensiveGameRating: number;
  defensiveGameRating: number;
  goals: number;
  assists: number;
  points: number;
  plusMinus: number;
  shotsOnGoal: number;
  missedShots: number;
  blockedShots: number;
  pim: number;
  hits: number;
  takeaways: number;
  giveaways: number;
  faceoffs: number;
  faceoffsWon: number;
  faceoffPct: number;
  shifts: number;
  timeOnIce: number;
  ppTimeOnIce: number;
  shTimeOnIce: number;
  team_shots_on: number;
  team_shots_against_on: number;
  team_shots_missed_on: number;
  team_shots_missed_against_on: number;
  team_shots_blocked_on: number;
  team_shots_blocked_against_on: number;
  team_goals_on: number;
  team_goals_against_on: number;
  team_shots_off: number;
  team_shots_against_off: number;
  team_shots_missed_off: number;
  team_shots_missed_against_off: number;
  team_shots_blocked_off: number;
  team_shots_blocked_against_off: number;
  team_goals_off: number;
  team_goals_against_off: number;
  oz_starts: number;
  nz_starts: number;
  dz_starts: number;
  team_oz_starts: number;
  team_nz_starts: number;
  team_dz_starts: number;
  sq0: number;
  sq1: number;
  sq2: number;
  sq3: number;
  sq4: number;
};

export type Goalie_Boxscore = {
  season: number;
  league: number;
  gameID: number;
  slug: number;
  playerID: number;
  name: string;
  teamID: number;
  teamAbbr: string;
  isHome: boolean;
  opponentTeamID: number;
  opponentAbbr: string;
  date: string;
  type: string;
  gameRating: number;
  shotsAgainst: number;
  goalsAgainst: number;
  saves: number;
  savePct: number;
  minutesPlayed: string;
  PIM: number;
  descision: boolean;
};

export type TeamInfo = {
  id: number;
  league: number;
  name: string;
  nickname: string;
  seasons?: number;
  season?: number;
  wins: number;
  losses: number;
  overtimeLosses: number;
  shootoutWins: number;
  shootoutLosses: number;
  points: number;
  goalsFor: number;
  goalsAgainst: number;
  winPercent: number;
};

export type PlayerHistory = Partial<Player> & {
  season?: number;
  seasons?: number;
  evTimeOnIce: number;
  evGoals: number;
  evAssists: number;
  evPoints: number;
  teamAbbr: string;
  stillActive: boolean;
  isRookie: boolean;
};

export type GoalieHistory = Partial<Goalie> & {
  seasons?: number;
  season?: number;
  teamAbbr: string;
  stillActive: boolean;
  isRookie: boolean;
};

export type TeamHistory = Partial<TeamInfo> & {
  goalsDiff: number;
  leagueRank?: number;
  divisionRank?: number;
  conferenceRank?: number;
  S?: number;
  SA?: number;
  FOPct?: number;
  SB?: number;
  H?: number;
  TkA?: number;
  GvA?: number;
  PIMPerG?: number;
  PPO?: number;
  PPG?: number;
  PPPercent?: number;
  SHGA?: number;
  SHO?: number;
  PPGA?: number;
  PKPercent?: number;
  playoffResult?: string;
  playoffWins: number;
  playoffLosses: number;
  finalsWon?: number;
  finalsLost?: number;
  round3?: number;
  round2?: number;
  round1?: number;
  missed?: number;
  gold?: number;
  silver?: number;
  bronze?: number;
  bronzeLosers?: number;
};
